// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: calculator.proto

#include "calculator.pb.h"
#include "calculator.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace calculator {

static const char* Calculator_method_names[] = {
  "/calculator.Calculator/Plus",
  "/calculator.Calculator/Minus",
};

std::unique_ptr< Calculator::Stub> Calculator::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Calculator::Stub> stub(new Calculator::Stub(channel));
  return stub;
}

Calculator::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Plus_(Calculator_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Minus_(Calculator_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Calculator::Stub::Plus(::grpc::ClientContext* context, const ::calculator::Request& request, ::calculator::Response* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Plus_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::calculator::Response>* Calculator::Stub::AsyncPlusRaw(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::calculator::Response>::Create(channel_.get(), cq, rpcmethod_Plus_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::calculator::Response>* Calculator::Stub::PrepareAsyncPlusRaw(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::calculator::Response>::Create(channel_.get(), cq, rpcmethod_Plus_, context, request, false);
}

::grpc::Status Calculator::Stub::Minus(::grpc::ClientContext* context, const ::calculator::Request& request, ::calculator::Response* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Minus_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::calculator::Response>* Calculator::Stub::AsyncMinusRaw(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::calculator::Response>::Create(channel_.get(), cq, rpcmethod_Minus_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::calculator::Response>* Calculator::Stub::PrepareAsyncMinusRaw(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::calculator::Response>::Create(channel_.get(), cq, rpcmethod_Minus_, context, request, false);
}

Calculator::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Calculator_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Calculator::Service, ::calculator::Request, ::calculator::Response>(
          std::mem_fn(&Calculator::Service::Plus), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Calculator_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Calculator::Service, ::calculator::Request, ::calculator::Response>(
          std::mem_fn(&Calculator::Service::Minus), this)));
}

Calculator::Service::~Service() {
}

::grpc::Status Calculator::Service::Plus(::grpc::ServerContext* context, const ::calculator::Request* request, ::calculator::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Calculator::Service::Minus(::grpc::ServerContext* context, const ::calculator::Request* request, ::calculator::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace calculator

