// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: calculator.proto
#ifndef GRPC_calculator_2eproto__INCLUDED
#define GRPC_calculator_2eproto__INCLUDED

#include "calculator.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace calculator {

class Calculator final {
 public:
  static constexpr char const* service_full_name() {
    return "calculator.Calculator";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Plus(::grpc::ClientContext* context, const ::calculator::Request& request, ::calculator::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::calculator::Response>> AsyncPlus(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::calculator::Response>>(AsyncPlusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::calculator::Response>> PrepareAsyncPlus(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::calculator::Response>>(PrepareAsyncPlusRaw(context, request, cq));
    }
    virtual ::grpc::Status Minus(::grpc::ClientContext* context, const ::calculator::Request& request, ::calculator::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::calculator::Response>> AsyncMinus(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::calculator::Response>>(AsyncMinusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::calculator::Response>> PrepareAsyncMinus(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::calculator::Response>>(PrepareAsyncMinusRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::calculator::Response>* AsyncPlusRaw(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::calculator::Response>* PrepareAsyncPlusRaw(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::calculator::Response>* AsyncMinusRaw(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::calculator::Response>* PrepareAsyncMinusRaw(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Plus(::grpc::ClientContext* context, const ::calculator::Request& request, ::calculator::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::calculator::Response>> AsyncPlus(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::calculator::Response>>(AsyncPlusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::calculator::Response>> PrepareAsyncPlus(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::calculator::Response>>(PrepareAsyncPlusRaw(context, request, cq));
    }
    ::grpc::Status Minus(::grpc::ClientContext* context, const ::calculator::Request& request, ::calculator::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::calculator::Response>> AsyncMinus(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::calculator::Response>>(AsyncMinusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::calculator::Response>> PrepareAsyncMinus(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::calculator::Response>>(PrepareAsyncMinusRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::calculator::Response>* AsyncPlusRaw(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::calculator::Response>* PrepareAsyncPlusRaw(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::calculator::Response>* AsyncMinusRaw(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::calculator::Response>* PrepareAsyncMinusRaw(::grpc::ClientContext* context, const ::calculator::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Plus_;
    const ::grpc::internal::RpcMethod rpcmethod_Minus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Plus(::grpc::ServerContext* context, const ::calculator::Request* request, ::calculator::Response* response);
    virtual ::grpc::Status Minus(::grpc::ServerContext* context, const ::calculator::Request* request, ::calculator::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Plus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Plus() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Plus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Plus(::grpc::ServerContext* context, const ::calculator::Request* request, ::calculator::Response* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPlus(::grpc::ServerContext* context, ::calculator::Request* request, ::grpc::ServerAsyncResponseWriter< ::calculator::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Minus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Minus() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Minus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Minus(::grpc::ServerContext* context, const ::calculator::Request* request, ::calculator::Response* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMinus(::grpc::ServerContext* context, ::calculator::Request* request, ::grpc::ServerAsyncResponseWriter< ::calculator::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Plus<WithAsyncMethod_Minus<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Plus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Plus() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Plus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Plus(::grpc::ServerContext* context, const ::calculator::Request* request, ::calculator::Response* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Minus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Minus() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Minus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Minus(::grpc::ServerContext* context, const ::calculator::Request* request, ::calculator::Response* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Plus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Plus() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::calculator::Request, ::calculator::Response>(std::bind(&WithStreamedUnaryMethod_Plus<BaseClass>::StreamedPlus, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Plus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Plus(::grpc::ServerContext* context, const ::calculator::Request* request, ::calculator::Response* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPlus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::calculator::Request,::calculator::Response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Minus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Minus() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::calculator::Request, ::calculator::Response>(std::bind(&WithStreamedUnaryMethod_Minus<BaseClass>::StreamedMinus, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Minus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Minus(::grpc::ServerContext* context, const ::calculator::Request* request, ::calculator::Response* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMinus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::calculator::Request,::calculator::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Plus<WithStreamedUnaryMethod_Minus<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Plus<WithStreamedUnaryMethod_Minus<Service > > StreamedService;
};

}  // namespace calculator


#endif  // GRPC_calculator_2eproto__INCLUDED
