// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

#ifndef PROTOBUF_calculator_2eproto__INCLUDED
#define PROTOBUF_calculator_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_calculator_2eproto();
void protobuf_AssignDesc_calculator_2eproto();
void protobuf_ShutdownFile_calculator_2eproto();

class Request;
class Response;

// ===================================================================

class Request : public ::google::protobuf::Message {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  void Swap(Request* other);

  // implements Message ----------------------------------------------

  Request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 lhs = 1;
  inline bool has_lhs() const;
  inline void clear_lhs();
  static const int kLhsFieldNumber = 1;
  inline ::google::protobuf::int32 lhs() const;
  inline void set_lhs(::google::protobuf::int32 value);

  // required int32 rhs = 2;
  inline bool has_rhs() const;
  inline void clear_rhs();
  static const int kRhsFieldNumber = 2;
  inline ::google::protobuf::int32 rhs() const;
  inline void set_rhs(::google::protobuf::int32 value);

  // required int32 op = 3;
  inline bool has_op() const;
  inline void clear_op();
  static const int kOpFieldNumber = 3;
  inline ::google::protobuf::int32 op() const;
  inline void set_op(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Request)
 private:
  inline void set_has_lhs();
  inline void clear_has_lhs();
  inline void set_has_rhs();
  inline void clear_has_rhs();
  inline void set_has_op();
  inline void clear_has_op();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 lhs_;
  ::google::protobuf::int32 rhs_;
  ::google::protobuf::int32 op_;
  friend void  protobuf_AddDesc_calculator_2eproto();
  friend void protobuf_AssignDesc_calculator_2eproto();
  friend void protobuf_ShutdownFile_calculator_2eproto();

  void InitAsDefaultInstance();
  static Request* default_instance_;
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  void Swap(Response* other);

  // implements Message ----------------------------------------------

  Response* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int64 result() const;
  inline void set_result(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Response)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 result_;
  friend void  protobuf_AddDesc_calculator_2eproto();
  friend void protobuf_AssignDesc_calculator_2eproto();
  friend void protobuf_ShutdownFile_calculator_2eproto();

  void InitAsDefaultInstance();
  static Response* default_instance_;
};
// ===================================================================


// ===================================================================

// Request

// required int32 lhs = 1;
inline bool Request::has_lhs() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_lhs() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_lhs() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_lhs() {
  lhs_ = 0;
  clear_has_lhs();
}
inline ::google::protobuf::int32 Request::lhs() const {
  // @@protoc_insertion_point(field_get:Request.lhs)
  return lhs_;
}
inline void Request::set_lhs(::google::protobuf::int32 value) {
  set_has_lhs();
  lhs_ = value;
  // @@protoc_insertion_point(field_set:Request.lhs)
}

// required int32 rhs = 2;
inline bool Request::has_rhs() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request::set_has_rhs() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request::clear_has_rhs() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request::clear_rhs() {
  rhs_ = 0;
  clear_has_rhs();
}
inline ::google::protobuf::int32 Request::rhs() const {
  // @@protoc_insertion_point(field_get:Request.rhs)
  return rhs_;
}
inline void Request::set_rhs(::google::protobuf::int32 value) {
  set_has_rhs();
  rhs_ = value;
  // @@protoc_insertion_point(field_set:Request.rhs)
}

// required int32 op = 3;
inline bool Request::has_op() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Request::set_has_op() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Request::clear_has_op() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Request::clear_op() {
  op_ = 0;
  clear_has_op();
}
inline ::google::protobuf::int32 Request::op() const {
  // @@protoc_insertion_point(field_get:Request.op)
  return op_;
}
inline void Request::set_op(::google::protobuf::int32 value) {
  set_has_op();
  op_ = value;
  // @@protoc_insertion_point(field_set:Request.op)
}

// -------------------------------------------------------------------

// Response

// required int64 result = 1;
inline bool Response::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response::clear_result() {
  result_ = GOOGLE_LONGLONG(0);
  clear_has_result();
}
inline ::google::protobuf::int64 Response::result() const {
  // @@protoc_insertion_point(field_get:Response.result)
  return result_;
}
inline void Response::set_result(::google::protobuf::int64 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:Response.result)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_calculator_2eproto__INCLUDED
