// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "calculator.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* Calculator_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Calculator_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_calculator_2eproto() {
  protobuf_AddDesc_calculator_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "calculator.proto");
  GOOGLE_CHECK(file != NULL);
  Calculator_descriptor_ = file->message_type(0);
  static const int Calculator_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Calculator, op_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Calculator, lhs_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Calculator, rhs_),
  };
  Calculator_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Calculator_descriptor_,
      Calculator::default_instance_,
      Calculator_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Calculator, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Calculator, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Calculator));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_calculator_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Calculator_descriptor_, &Calculator::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_calculator_2eproto() {
  delete Calculator::default_instance_;
  delete Calculator_reflection_;
}

void protobuf_AddDesc_calculator_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020calculator.proto\"2\n\nCalculator\022\n\n\002op\030\001"
    " \002(\007\022\013\n\003lhs\030\002 \002(\007\022\013\n\003rhs\030\003 \002(\007", 70);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "calculator.proto", &protobuf_RegisterTypes);
  Calculator::default_instance_ = new Calculator();
  Calculator::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_calculator_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_calculator_2eproto {
  StaticDescriptorInitializer_calculator_2eproto() {
    protobuf_AddDesc_calculator_2eproto();
  }
} static_descriptor_initializer_calculator_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Calculator::kOpFieldNumber;
const int Calculator::kLhsFieldNumber;
const int Calculator::kRhsFieldNumber;
#endif  // !_MSC_VER

Calculator::Calculator()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Calculator)
}

void Calculator::InitAsDefaultInstance() {
}

Calculator::Calculator(const Calculator& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Calculator)
}

void Calculator::SharedCtor() {
  _cached_size_ = 0;
  op_ = 0u;
  lhs_ = 0u;
  rhs_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Calculator::~Calculator() {
  // @@protoc_insertion_point(destructor:Calculator)
  SharedDtor();
}

void Calculator::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Calculator::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Calculator::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Calculator_descriptor_;
}

const Calculator& Calculator::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_calculator_2eproto();
  return *default_instance_;
}

Calculator* Calculator::default_instance_ = NULL;

Calculator* Calculator::New() const {
  return new Calculator;
}

void Calculator::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Calculator*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(op_, rhs_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Calculator::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Calculator)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required fixed32 op = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &op_)));
          set_has_op();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_lhs;
        break;
      }

      // required fixed32 lhs = 2;
      case 2: {
        if (tag == 21) {
         parse_lhs:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &lhs_)));
          set_has_lhs();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_rhs;
        break;
      }

      // required fixed32 rhs = 3;
      case 3: {
        if (tag == 29) {
         parse_rhs:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &rhs_)));
          set_has_rhs();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Calculator)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Calculator)
  return false;
#undef DO_
}

void Calculator::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Calculator)
  // required fixed32 op = 1;
  if (has_op()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(1, this->op(), output);
  }

  // required fixed32 lhs = 2;
  if (has_lhs()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(2, this->lhs(), output);
  }

  // required fixed32 rhs = 3;
  if (has_rhs()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(3, this->rhs(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Calculator)
}

::google::protobuf::uint8* Calculator::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Calculator)
  // required fixed32 op = 1;
  if (has_op()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(1, this->op(), target);
  }

  // required fixed32 lhs = 2;
  if (has_lhs()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(2, this->lhs(), target);
  }

  // required fixed32 rhs = 3;
  if (has_rhs()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(3, this->rhs(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Calculator)
  return target;
}

int Calculator::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required fixed32 op = 1;
    if (has_op()) {
      total_size += 1 + 4;
    }

    // required fixed32 lhs = 2;
    if (has_lhs()) {
      total_size += 1 + 4;
    }

    // required fixed32 rhs = 3;
    if (has_rhs()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Calculator::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Calculator* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Calculator*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Calculator::MergeFrom(const Calculator& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_op()) {
      set_op(from.op());
    }
    if (from.has_lhs()) {
      set_lhs(from.lhs());
    }
    if (from.has_rhs()) {
      set_rhs(from.rhs());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Calculator::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Calculator::CopyFrom(const Calculator& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Calculator::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void Calculator::Swap(Calculator* other) {
  if (other != this) {
    std::swap(op_, other->op_);
    std::swap(lhs_, other->lhs_);
    std::swap(rhs_, other->rhs_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Calculator::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Calculator_descriptor_;
  metadata.reflection = Calculator_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
