// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

public final class CalculatorOuterClass {
  private CalculatorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CalculatorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Calculator)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 op = 1;</code>
     */
    boolean hasOp();
    /**
     * <code>required int32 op = 1;</code>
     */
    int getOp();

    /**
     * <code>required int32 lhs = 2;</code>
     */
    boolean hasLhs();
    /**
     * <code>required int32 lhs = 2;</code>
     */
    int getLhs();

    /**
     * <code>required int32 rhs = 3;</code>
     */
    boolean hasRhs();
    /**
     * <code>required int32 rhs = 3;</code>
     */
    int getRhs();
  }
  /**
   * Protobuf type {@code Calculator}
   *
   * <pre>
   * $ protoc calculator.proto --cpp_out=.
   * </pre>
   */
  public static final class Calculator extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Calculator)
      CalculatorOrBuilder {
    // Use Calculator.newBuilder() to construct.
    private Calculator(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Calculator(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Calculator defaultInstance;
    public static Calculator getDefaultInstance() {
      return defaultInstance;
    }

    public Calculator getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Calculator(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              op_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lhs_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rhs_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CalculatorOuterClass.internal_static_Calculator_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CalculatorOuterClass.internal_static_Calculator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CalculatorOuterClass.Calculator.class, CalculatorOuterClass.Calculator.Builder.class);
    }

    public static com.google.protobuf.Parser<Calculator> PARSER =
        new com.google.protobuf.AbstractParser<Calculator>() {
      public Calculator parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Calculator(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Calculator> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int OP_FIELD_NUMBER = 1;
    private int op_;
    /**
     * <code>required int32 op = 1;</code>
     */
    public boolean hasOp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 op = 1;</code>
     */
    public int getOp() {
      return op_;
    }

    public static final int LHS_FIELD_NUMBER = 2;
    private int lhs_;
    /**
     * <code>required int32 lhs = 2;</code>
     */
    public boolean hasLhs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 lhs = 2;</code>
     */
    public int getLhs() {
      return lhs_;
    }

    public static final int RHS_FIELD_NUMBER = 3;
    private int rhs_;
    /**
     * <code>required int32 rhs = 3;</code>
     */
    public boolean hasRhs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 rhs = 3;</code>
     */
    public int getRhs() {
      return rhs_;
    }

    private void initFields() {
      op_ = 0;
      lhs_ = 0;
      rhs_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLhs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRhs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, op_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, lhs_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, rhs_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, op_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lhs_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rhs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CalculatorOuterClass.Calculator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CalculatorOuterClass.Calculator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CalculatorOuterClass.Calculator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CalculatorOuterClass.Calculator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CalculatorOuterClass.Calculator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CalculatorOuterClass.Calculator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CalculatorOuterClass.Calculator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CalculatorOuterClass.Calculator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CalculatorOuterClass.Calculator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CalculatorOuterClass.Calculator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CalculatorOuterClass.Calculator prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Calculator}
     *
     * <pre>
     * $ protoc calculator.proto --cpp_out=.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Calculator)
        CalculatorOuterClass.CalculatorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CalculatorOuterClass.internal_static_Calculator_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CalculatorOuterClass.internal_static_Calculator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CalculatorOuterClass.Calculator.class, CalculatorOuterClass.Calculator.Builder.class);
      }

      // Construct using CalculatorOuterClass.Calculator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        op_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        lhs_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        rhs_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CalculatorOuterClass.internal_static_Calculator_descriptor;
      }

      public CalculatorOuterClass.Calculator getDefaultInstanceForType() {
        return CalculatorOuterClass.Calculator.getDefaultInstance();
      }

      public CalculatorOuterClass.Calculator build() {
        CalculatorOuterClass.Calculator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CalculatorOuterClass.Calculator buildPartial() {
        CalculatorOuterClass.Calculator result = new CalculatorOuterClass.Calculator(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.op_ = op_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lhs_ = lhs_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rhs_ = rhs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CalculatorOuterClass.Calculator) {
          return mergeFrom((CalculatorOuterClass.Calculator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CalculatorOuterClass.Calculator other) {
        if (other == CalculatorOuterClass.Calculator.getDefaultInstance()) return this;
        if (other.hasOp()) {
          setOp(other.getOp());
        }
        if (other.hasLhs()) {
          setLhs(other.getLhs());
        }
        if (other.hasRhs()) {
          setRhs(other.getRhs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOp()) {
          
          return false;
        }
        if (!hasLhs()) {
          
          return false;
        }
        if (!hasRhs()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CalculatorOuterClass.Calculator parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CalculatorOuterClass.Calculator) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int op_ ;
      /**
       * <code>required int32 op = 1;</code>
       */
      public boolean hasOp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 op = 1;</code>
       */
      public int getOp() {
        return op_;
      }
      /**
       * <code>required int32 op = 1;</code>
       */
      public Builder setOp(int value) {
        bitField0_ |= 0x00000001;
        op_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 op = 1;</code>
       */
      public Builder clearOp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        op_ = 0;
        onChanged();
        return this;
      }

      private int lhs_ ;
      /**
       * <code>required int32 lhs = 2;</code>
       */
      public boolean hasLhs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 lhs = 2;</code>
       */
      public int getLhs() {
        return lhs_;
      }
      /**
       * <code>required int32 lhs = 2;</code>
       */
      public Builder setLhs(int value) {
        bitField0_ |= 0x00000002;
        lhs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 lhs = 2;</code>
       */
      public Builder clearLhs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lhs_ = 0;
        onChanged();
        return this;
      }

      private int rhs_ ;
      /**
       * <code>required int32 rhs = 3;</code>
       */
      public boolean hasRhs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 rhs = 3;</code>
       */
      public int getRhs() {
        return rhs_;
      }
      /**
       * <code>required int32 rhs = 3;</code>
       */
      public Builder setRhs(int value) {
        bitField0_ |= 0x00000004;
        rhs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rhs = 3;</code>
       */
      public Builder clearRhs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rhs_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Calculator)
    }

    static {
      defaultInstance = new Calculator(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Calculator)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Calculator_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Calculator_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020calculator.proto\"2\n\nCalculator\022\n\n\002op\030\001" +
      " \002(\005\022\013\n\003lhs\030\002 \002(\005\022\013\n\003rhs\030\003 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Calculator_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Calculator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Calculator_descriptor,
        new java.lang.String[] { "Op", "Lhs", "Rhs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
